KeepAccount/Models/ErrorViewModel.cs
using System;

namespace KeepAccount.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KeepAccount/Models/Expenditure.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using static System.Int32;

namespace KeepAccount.Models
{
    public class Expenditure
    {
        [Required(ErrorMessage = "* Date is required")]
        public DateTime? Date { get; set; }
        [Required(ErrorMessage = "* Name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "* Type is required")]
        public string Type { get; set; }
        [Required(ErrorMessage = "* Amount is required")]
        [Range(1, MaxValue, ErrorMessage = "* Amount needs to more than 0")]
        public int? Amount { get; set; }
        public string Note { get; set; }
    }
}

KeepAccount/Models/PageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KeepAccount.Models
{
    public class PageViewModel
    {
        public Expenditure Expenditure { get; set; }
        public List<Expenditure> Expenditures { get; set; }
    }
}

KeepAccount/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KeepAccount.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace KeepAccount.Controllers
{
    [Route("api/")] //[controller]
    [ApiController]
    public class ApiController : ControllerBase
    {
        private readonly List<Expenditure> _data = KeepAccountController.Data;

        // GET: api/records
        [Route("records")]
        [HttpGet]
        public JsonResult Records()
        {
            return new JsonResult(_data);
        }
    }
}

KeepAccount/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using KeepAccount.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace KeepAccount.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KeepAccount/Controllers/KeepAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KeepAccount.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace KeepAccount.Controllers
{
    public class KeepAccountController : Controller
    {
        public static List<Expenditure> Data = new List<Expenditure>();

        // GET: KeepAccountController
        public ActionResult Index()
        {
            var model = new PageViewModel {Expenditures = Data};

            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Create(Expenditure expenditure)
        {
            if (expenditure.Amount == 0)
            {
                
                ModelState.AddModelError(nameof(expenditure.Amount), "Please enter your name");
            } 
            if (!ModelState.IsValid)
                return View("Index", new PageViewModel { Expenditures = Data, Expenditure = expenditure});

            Data.Add(expenditure);
            return RedirectToAction("Index");
        }
    }
}

KeepAccount/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

KeepAccount/Views/KeepAccount/Index.cshtml
@model PageViewModel

<h1 class="display-4">Manage Keep Account</h1>

<div style="width: 30%; height: 80%; display: inline-block;">
    <partial name="_Create" model="Model.Expenditure" />
</div>

<div style="width: 65%; height: 80%; display: inline-block; vertical-align: top; float: right; padding: 20px;">
    <partial name="_View" model="Model.Expenditures" />
</div>

KeepAccount/Views/KeepAccount/_Create.cshtml
@model Expenditure

<div>
    <form asp-controller="KeepAccount" asp-action="Create" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div>
            <label asp-for="Date">Date :</label>
            <span asp-validation-for="Date" class="text-danger"></span>
            <input asp-for="Date" type="date" class="form-control">
            <label asp-for="Name">Name :</label>
            <span asp-validation-for="Name" class="text-danger"></span>
            <input asp-for="Name" class="form-control">
            <label>Type :</label>
            <span asp-validation-for="Type" class="text-danger"></span>
            <select asp-for="Type" id="selectType" class="form-control" style="width: 100%;">
                <option selected disabled> Select </option>
                <option value="Food"> Food </option>
                <option value="Transportation"> Transportation </option>
                <option value="Entertainment"> Entertainment </option>
                <option value="Others"> Others </option>
            </select>
            <label asp-for="Amount">Amount :</label>
            <span asp-validation-for="Amount" class="text-danger"></span>
            <input asp-for="Amount" class="form-control">
            <label asp-for="Note">Note :</label>
            <span asp-validation-for="Note" class="text-danger"></span>
            <input asp-for="Note" class="form-control">
            <div style="padding: 5px 0;">
                <button class="btn btn-info">Add</button>
            </div>
        </div>
    </form>
</div>

<style>
    th, td {
        border-bottom: 1px solid #AAAAAA;
    }
</style>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(window).load(function() {
            if (@Model !== null) {
                $('#selectType option[value=' + @Model.Type + ']').attr('selected', 'selected');
            }
        });
    </script>
}

KeepAccount/Views/KeepAccount/_View.cshtml
@model List<Expenditure>

<div style="border:2px #ccc solid; border-radius: 10px; padding: 7px; height: 340px; overflow: auto;">
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Name</th>
                <th>Type</th>
                <th>Amount</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var expenditure in Model)
            {
                <tr>
                    @{
                        var date = expenditure.Date.HasValue? expenditure.Date.Value.ToShortDateString() : string.Empty;
                    }
                    <td>@date</td>
                    <td>@expenditure.Name</td>
                    <td>@expenditure.Type</td>
                    <td>@expenditure.Amount</td>
                    <td>@expenditure.Note</td>
                </tr>
            }
        </tbody>
    </table>
</div>

KeepAccount/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KeepAccount</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KeepAccount</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="KeepAccount" asp-action="Index">Manage Keep Account</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - KeepAccount - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>